---

- include_tasks: gsettings.yml
  vars:
    path: "{{ item.path }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ gsettings }}"
  when: gsettings is defined and gsettings|length > 0
